alias: Koeling aan
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.ecodan_heatpump_zone_1_room_temp
    for:
      hours: 1
      minutes: 0
      seconds: 0
    above: 22.5
conditions: []
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: Cool Flow Temperature
    target:
      entity_id: select.ecodan_heatpump_selected_operating_mode
mode: single
