alias: Nachtverlaging
description: ""
triggers:
  - trigger: time
    at: "01:00:00"
conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: select.ecodan_heatpump_selected_operating_mode
        state: Heat Target Temperature
      - condition: numeric_state
        entity_id: sensor.temperatuur_dag_vooruitzicht
        above: 5
actions:
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 19.5
    target:
      entity_id: climate.ecodan_heatpump_zone_1_climate
mode: single
