alias: Koelen toestaan
description: ""
triggers:
  - at: "08:00:00"
    trigger: time
  - at: "10:00:00"
    trigger: time
  - at: "12:00:00"
    trigger: time
  - at: "14:00:00"
    trigger: time
  - at: "16:00:00"
    trigger: time
  - at: "18:00:00"
    trigger: time
conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: select.ecodan_heatpump_selected_operating_mode
        state: Cool Flow Temperature
      - condition: numeric_state
        entity_id: sensor.ecodan_heatpump_zone_1_room_temp
        above: 22.5
      - condition: state
        entity_id: sensor.ecodan_heatpump_operation_mode
        state: "Off"
        for:
          hours: 1
          minutes: 0
          seconds: 0
      - condition: state
        entity_id: switch.ecodan_heatpump_server_control_enable_disable
        state: "on"
actions:
  - action: switch.turn_off
    target:
      entity_id: switch.ecodan_heatpump_server_control_zone_1_prohibit_cooling
    data: {}
mode: single
